### ISSUE TITLE
How to save figures?

### ISSUE THREAD

**Issue by Junjie-Hu** [zktuong/ktplotspy#22]
Hi,
   How to save figures?  I used "plt.savefig()", but it did not work.

**Comment by zktuong** [comment]
Hi, sorry i haven’t had time to update the docs. Basically plot_cpdb is written with plotnine, so you can yse plotnine’s method to save those plots. 

for the remaining functions, plt.savefig should work.

**Comment by zktuong** [comment]
sorry i gave the wrong instruction for `plot_cpdb`. p.save() should work. you can take a look at the updated tutorial

**Comment by Junjie-Hu** [comment]
Thanks a lot for your kind response!

发件人: Zewen Kelvin Tuong
发送时间: 2023年4月13日 8:57
收件人: zktuong/ktplotspy
抄送: JHu; Author
主题: Re: [zktuong/ktplotspy] How to save figures? (Issue #22)

sorry i gave the wrong instruction for plot_cpdb. p.save() should work. you can take a look at the updated tutorial
