### ISSUE TITLE
Plot using mtx format (not .h5ad)

### ISSUE THREAD

**Issue by DaianeH** [zktuong/ktplotspy#29]
Hi,

I'm new to cellphonedb and just run it on a Seurat object in mtx format (as described here):
https://github.com/ventolab/CellphoneDB/blob/master/notebooks/DEGs_calculation/0_prepare_your_data_from_Seurat.ipynb
not in a .h5ad format. If I don't have a .h5ad, how can I define the adata parameter to plot using ktplotspy?

Thank you in advance,

**Comment by zktuong** [comment]
hi @DaianeH,

actually there's is an R-package for `ktplots` https://github.com/zktuong/ktplots. You can feed your Seurat object to it (but generally works better as SingleCellExperiment).
