### ISSUE TITLE
Add parameters for kpy.plot_cpdb_heatmap

### ISSUE THREAD

**Issue by QqQss** [zktuong/ktplotspy#66]
Hi, thanks for your great tool!

I kindly request you to add the parameter 'separator' to your plot functions. Previously, when running cpdb analysis, one may have used a custom separator to separate interacted cell pairs with the 'separator' parameter. The current plot functions do not seem compatible with this feature as they defaultly use '|' as the separator, resulting in errors.

Thanks again!

**Comment by zktuong** [comment]
Hi, thanks for the comments! Ok should be an easy fix. @ali-harasty can we create another PR on this?

**Comment by zktuong** [comment]
ok #67 has been merged! please reinstall with `pip install git+https://www.github.com/zktuong/ktplotspy.git`
